apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-deploy-pvc
  namespace: mgt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "prometheus-deploy"
  resources:
    requests:
      storage: 30Gi
