apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-deploy-pv
  namespace: mgt
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  storageClassName: "prometheus-deploy"
  claimRef:
    name: prometheus-deploy-pvc
    namespace: mgt
  nfs:
    server: 10.210.2.208
    path: /monitoring
